version: '3.8'

services:
  proxy:
    image: "mitmproxy/mitmproxy:${PROXY_VERSION-latest}"
    container_name: "${PROXY_CONTAINER_NAME-proxy}"
    networks:
      devnet:
    ports:
      - "${PROXY_HOST_PORT-8080}:8080"
    volumes:
      - "${PROXY_VOLUME_DIR:-/tmp/mitmproxy}:/home/mitmproxy/.mitmproxy"


networks:
  devnet:
    name: ${DEVNET_NAME-devnet}
    external: true
